[package]
name = "video-encoding-wrapper"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "multimedia::video"]
description = "Opinionated tool to encode videos"
keywords = ["video"]
license = "MIT"
repository = "https://github.com/aexoden/video-encoding-wrapper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.80", features = ["backtrace"] }
av-metrics = "0.9.1"
av-metrics-decoders = { version = "0.3.1", features = ["y4m", "ffmpeg-the-third"] }
av-scenechange = { version = "0.10.0", default-features = false }
base16ct = { version = "0.2.0", features = ["alloc", "std"] }
cached = "0.48.1"
clap = { version = "4.4.18", features = ["derive"] }
crossbeam-queue = "0.3.11"
ffmpeg = { package = "ffmpeg-the-third", version = "1.2.2", features = ["serialize"] }
indicatif = "0.17.3"
number_prefix = "0.4.0"
plotters = { version = "0.3.5", default-features = false, features = ["svg_backend", "line_series"] }
prettytable-rs = "0.10.0"
rayon = "1.8.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.113"
sha2 = "0.10.6"
ssimulacra2 = { version = "0.4.0", default-features = false }
statrs = "0.16.0"
tokio = { version = "1.36.0", features = ["process"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
y4m = "0.8.0"

[profile.release]
lto = "fat"

[profile.dev]
incremental = true
opt-level = 3
