[package]
name = "video-encoding-wrapper"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities", "multimedia::video"]
description = "Opinionated tool to encode videos"
keywords = ["video"]
license = "MIT"
repository = "https://github.com/aexoden/video-encoding-wrapper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
av-scenechange = { version = "0.8.1", default-features = false }
base16ct = { version = "0.2.0", features = ["alloc", "std"] }
cached = "0.43.0"
clap = { version = "4.2.2", features = ["derive"] }
crossbeam-queue = "0.3.8"
ffmpeg = { package = "ffmpeg-the-third", version = "1.2.2", features = ["serialize"] }
indicatif = "0.17.3"
number_prefix = "0.4.0"
rayon = "1.7.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
sha2 = "0.10.6"
tokio = { version = "1.28.0", features = ["process"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
y4m = "0.7.0"

[profile.release]
lto = "fat"

[profile.dev]
incremental = true
opt-level = 3
