[package]
name = "video-encoding-wrapper"
version = "0.1.0"
authors = ["Jason Lynch <jason@aexoden.com>"]
edition = "2021"
categories = ["command-line-utilities", "multimedia::video"]
description = "Opinionated tool to encode videos"
keywords = ["video"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/aexoden/video-encoding-wrapper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
future_incompatible = "warn"
let_underscore = "warn"

[lints.clippy]
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
restriction = { level = "warn", priority = -1 }
arithmetic_side_effects = "allow"
blanket_clippy_restriction_lints = "allow"
exhaustive_enums = "allow"
exhaustive_structs = "allow"
float_arithmetic = "allow"
implicit_return = "allow"
missing_docs_in_private_items = "allow"
missing_errors_doc = "allow"
missing_inline_in_public_items = "allow"
multiple_crate_versions = "allow"
pattern_type_mismatch = "allow"
question_mark_used = "allow"
separated_literal_suffix = "allow"
shadow_reuse = "allow"
single_call_fn = "allow"
std_instead_of_alloc = "allow"
std_instead_of_core = "allow"

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
av-metrics = "0.9.1"
av-metrics-decoders = { version = "0.3.1", features = ["y4m", "ffmpeg-the-third"] }
av-scenechange = { version = "0.10.0", default-features = false }
base16ct = { version = "0.2.0", features = ["alloc", "std"] }
cached = "0.50.0"
clap = { version = "4.5.4", features = ["derive"] }
crossbeam-queue = "0.3.11"
ffmpeg = { package = "ffmpeg-the-third", version = "1.2.2", features = ["serialize"] }
indicatif = "0.17.8"
number_prefix = "0.4.0"
plotters = { version = "0.3.5", default-features = false, features = ["svg_backend", "line_series"] }
prettytable-rs = "0.10.0"
rayon = "1.10.0"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
sha2 = "0.10.6"
ssimulacra2 = { version = "0.5.0", default-features = false }
statrs = "0.16.0"
tokio = { version = "1.37.0", features = ["process"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
y4m = "0.8.0"

[profile.release]
lto = "fat"

[profile.dev]
incremental = true
opt-level = 3
