[advisories]
ignore = [
  { id = "RUSTSEC-2024-0436", reason = "Caused by an indirect dependency by simba, and will be fixed in the next release." }
]

[bans]
multiple-versions = "allow"

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "WTFPL",
  "Zlib",
]
