[advisories]
version = 2
ignore = [
    "RUSTSEC-2024-0436",
]

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "NCSA",
    "Unicode-3.0",
    "WTFPL",
    "Zlib",
]
